### DISCUSSION TITLE
Hello, how do I connect this to mysql container during setup wizard?

### DISCUSSION THREAD

**Discussion by kreindo** [tgstation/tgstation-server-tools#1562] [Q&A] [answered]
I tried to connect it, but it always says 'unable to connect to any of the specified MySql host'
or
Access denied for user 'root'@'localhost'

**Comment by kreindo** [comment]
im using docker for tgstation-server, and docker compose from mysql docker hub, that includes adminer

**Reply by Cyberboss** [reply]
Can you post your docker-compose config?

**Reply by Cyberboss** [reply]
Note that TGS expects a valid `/tgs_config/appsettings.Production.yml` to be present at startup otherwise it will attempt to run the interactive setup wizard if I recall correctly.

**Reply by kreindo** [reply]
![](https://user-images.githubusercontent.com/38377576/247757302-eb71452d-1fc5-4f53-8db2-3c003b711623.png)

**Reply by Cyberboss** [reply, marked as answer]
The following setup will get you started. Note, I switched the database type to MariaDB for more modern support, it's also favored by most SS13 servers if that's your intention:
```
PS S:\garbage> ls


    Directory: S:\garbage


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        2023-06-21   7:43 PM                tgs_config
-a----        2023-06-21   9:22 PM            495 docker-compose.yml


PS S:\garbage> ls .\tgs_config\


    Directory: S:\garbage\tgs_config


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        2023-06-21   7:50 PM            705 appsettings.Production.yml


PS S:\garbage> cat .\docker-compose.yml
version: '3.1'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  tgs:
    image: tgstation/server
    restart: always
    init: true
    cap_add: [sys_nice]
    ports:
      - 5000:5000 # TGS Admin port
      - 1337:1337 # game port
    volumes:
      - S:/garbage/tgs_config:/config_data
      - S:/garbage/tgs_logs:/tgs_logs
PS S:\garbage> cat .\tgs_config\appsettings.Production.yml
General:
  MinimumPasswordLength: 15 # Change this if you wish
  GitHubAccessToken: # Add this to make GitHub requests not 429
  SetupWizardMode: Never
  ValidInstancePaths: /tgs_instances
  DeploymentDirectoryCopyTasksPerCore: 100 # Lower this if deployments are slow
Session:
  HighPriorityLiveDreamDaemon: true
ControlPanel:
  Enable: true
  AllowAnyOrigin: true
  PublicPath: # Adjust this if you plan to publicly host the webpanel
Database:
  DatabaseType: MariaDB
  ResetAdminPassword: false
  ConnectionString: Server=db;User Id=root;Database=tgs;Password=password
Security:
  OAuth: # See README.md for how to configure OAuth (Optional)
    GitHub:
    Discord:
    Keycloak:
PS S:\garbage> docker-compose up -d
[+] Building 0.0s (0/0)
[+] Running 4/4
 ✔ Network garbage_default      Created                                                                            0.0s
 ✔ Container garbage-tgs-1      Started                                                                            1.9s
 ✔ Container garbage-db-1       Started                                                                            1.8s
 ✔ Container garbage-adminer-1  Started                                                                            1.8s
PS S:\garbage>
```
A few things to note:

TGS needs to run as a DB user either with CREATE DATABASE permissions, or be pointed at an existing database that allows the user to edit the table definitions. For these reasons, it's easiest to give it root access for a quick and dirty setup.

If you're NOT running Windows, you'll also want to map `/tgs_instances` as a volume as that's where game data will be stored. The volume is not compatible with Docker for Windows though.

See the README.md for the full list of config options.
